### ISSUE TITLE
Maybe redundant

### ISSUE THREAD

**Issue by petemcfarlane** [rzane/classnames#1]
Hey, I came looking for a similar package to the node `classnames` and found this. But after a bit more digging I realised that the `class` attribute in Phoenix.HTML.Form can also take a list (of strings/atoms) and it already filters values that are `nil` or `false`. So with that in mind instead of 
```elixir
class = classnames([
  "foo": 1 + 1 == 2,
  bar: 1 == 0
])
```

You can just as easily write
```elixir
class = [
  1 + 1 == 2 and "foo",
  1 == 0 and :bar
]
```

You just have to switch the condition/classname around. I guess that kind of makes this `classnames` function redundant?

I didn't mean to take value from your work, just wanted share that there might be a better way (even if it's not very well documented anywhere!)

**Comment by rzane** [comment]
You're absolutely right, but there are a few caveats:
1. If I'm not mistaken, that works for HEEX templates and functions `Phoenix.HTML`, but I don't think that works for traditional EEX templates.
2. This library was released in 2016. At that time, this functionality was not available.
3. Some people might find this library to be more readable than the example you provided.

That being said, it might be worth mentioning that this functionality is available in the README. I'd happily accept a PR that documented this option for people using Phoenix LiveView.
